### ISSUE TITLE
Verificar se o nome do UserService está correto no arquivo TaskService

### ISSUE THREAD

**Issue by raiffhigor** [4lessandrodev/simple-ddd-app-example#1]
Bom dia Alessandro,

        Primeiro gostaria de parabenizar pelo trabalho deste repositório que está me ajudando muito a entender como organizar aplicações em DDD. 

        O ponto que gostaria de considerar é saber se foi proposital o uso do nome UserService no arquivo TaskService da pasta /src/modules/task/task.service.ts ou se o correto seria utilizar o nome TaskService para a classe?

        Desde já agradeço a atenção!
![alessandrodev](https://user-images.githubusercontent.com/20887238/180652799-9a39d97e-3fb7-4f7f-abc3-4619805e16f2.png)

**Comment by 4lessandrodev** [comment]
Que bom que está sendo útil para você @raiffhigor, 
O nome da classe realmente estava errado, esse é o problema de copiar e colar hahah.

Sucesso!
